### ISSUE TITLE
Updating to 0.17 - Uncaught ReferenceError: Elm is not defined

### ISSUE THREAD

**Issue by alanwilhelm** [moarwick/elm-webpack-starter#13]
Not sure what is causing this. Thoughts? I updated all of the libs and Main.elm file so it compiles with elm-make. It also compiles fine with Webpack but I get this in my browser console.
Uncaught ReferenceError: Elm is not defined

updated package.json:
![image](https://cloud.githubusercontent.com/assets/175353/15198384/e45aec6c-178b-11e6-99c8-96d8c5f8ad81.png)

elm-package.json:
![image](https://cloud.githubusercontent.com/assets/175353/15198418/1c38eab2-178c-11e6-934d-608db785ee29.png)

**Comment by MartinKavik** [comment]
Hi, I've got same problem - It's mainly due to incompatibility between [elm-webpack-loader](https://github.com/rtfeldman/elm-webpack-loader) and elm 0.17. They already [fixed](https://github.com/rtfeldman/elm-webpack-loader/pull/50) this a few hours ago.

So my quick solution:
**1.** Update **elm-webpack-loader** in the project root:  _(ncu = [npm-check-updates](https://www.npmjs.com/package/npm-check-updates))_

```
ncu -u && npm update
```

**2.** Elm-webpack-loader update breaks **elm-hot-loader** constraints, so I removed it:

```
npm uninstall elm-hot-loader --save-dev
```

**3.** Edit **_webpack.config.js**_

``` js
test: /\.elm$/,
exclude: [/elm-stuff/, /node_modules/],
//loader: 'elm-hot!elm-webpack'
loader: 'elm-webpack'
```

**4.** Edit _src /_ **_index.js**_

``` js
var Elm = require( './Main' );
Elm.Main.embed(document.getElementById( 'main' ));
```

**Comment by moarwick** [comment]
Thanks guys. Ver 0.17 intro'd quite a few "breaking" changes, per the [upgrade doc](https://github.com/elm-lang/elm-platform/blob/master/upgrade-docs/0.17.md). I made the updates, to the best of my (poor) Elm abilities. Yes, had to remove `elm-hot-loader` for the time being. Remember to repeat the install steps..
