### ISSUE TITLE
Move ownership to elm-community

### ISSUE THREAD

**Issue by eeue56** [moarwick/elm-webpack-starter#50]
Hi! I'm an owner of [elm-commmunity](https://github.com/elm-community/), a group dedicated to maintaining Elm packages that have proved to be popular. I'm also the maintainer of [elm-webpack-loader](https://github.com/elm-community/elm-webpack-loader/)

Since you are no longer maintaining this, it would be great if you could transfer this over to us. We'll take good care of it.

**Comment by eeue56** [comment]
cc @moarwick

**Comment by moarwick** [comment]
hi @eeue56. thanks for reaching out. it appears you are a legit Elm dev and the group a perfect place for this repo, so happy to do it. per this [article](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/), it appears you need to make me a "contributor" before I can transfer ownership?

**Comment by eeue56** [comment]
@moarwick Done :)

**Comment by moarwick** [comment]
hmm, just tried to transfer but getting `You don’t have the permission to create repositories on elm-community`

**Comment by eeue56** [comment]
@moarwick Hmm, how about adding me as an owner to this repo, then I'll transfer it?

**Comment by moarwick** [comment]
@eeue56 the transfer went through. i didn't realize there was an invite to elm-community i had to accept. anyway, all yours -- there goes my most popular repo!

One known issue is the `build` script, which is not Windows compatible currently (due to its use of the `mv` command). I couldn't find a clean move the assets via webpack, and I don't think there is a cross-platform move command ala `rimraf`. Perhaps going back to a flatter folder structure pre `0.7.0`.. also, good time to upgrade to Webpack 2?

Finally, you may want to edit the Readme to reflect the new URL, etc.

Thanks!

**Comment by eeue56** [comment]
@moarwick Thanks! I'll get through updating it today. I'll leave you as a collaborator should you return to Elm at some point!

**Comment by littleStudent** [comment]
Not relevant to this "issue" but never the less, I wanted to say thank you @moarwick.
I use this as a starter for all elm projects I do and I never had a real problem 👍 . thanks for the work.
